server:
  port: 8088 #ovveride in second instance with 8089
  servlet:
    session:
      cookie:
        same-site: lax
spring:
  jmx: enabled
pl.marcinzygmunt:
  pgvector:
    host: localhost
    port: 5433
    db: vectordb
    table: embeddings
    username: testuser
    password: testpwd
  ollama-host: localhost
  ollama-port: 11434
  ollama-language-model: "llama3:latest" # try "mistral", "llama2", "codellama", "phi" or "tinyllama"
  storage-type: pgVector #inMemory #pgsql with pgVector