version: '3.8'
services:
  ollama-server:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_MODELS=/usr/ollama_models #added for limited storage problems - use with WSL2
    ports:
      - "11434:11434"
    volumes:
      - /ollama:/root
    restart: unless-stopped
    command: "ollama run llama3"
    # environment:
    #   - gpus=all
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres: