version: '3.8'
services:
  ollama-server:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - /ollama:/root/.ollama
    restart: unless-stopped
    # environment:
    #   - gpus=all
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    volumes:
      - /ollama/webui:/app/backend/data
    ports:
      - "3010:8080"
    # environment:
    #   - OLLAMA_API_BASE_URL=http://localhost:11434/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres: